require: rubocop-rails

AllCops:
    Exclude:
        - 'spec/**/*'
        - 'db/**/*'
        - 'config/**/*'
        - 'bin/*'
        - 'config.ru'
        - 'Gemfile'
        - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

